CREATE TABLE STOCK (
	STOCK_ID	NUMBER		NOT NULL,
	STOCK_CODE	VARCHAR(10)	NOT	NULL,
	STOCK_NAME	VARCHAR(20)	NOT	NULL,
	CONSTRAINT PK_STOCK_ID	PRIMARY KEY (STOCK_ID),
	CONSTRAINT STOCK_CODE UNIQUE (STOCK_CODE),
	CONSTRAINT STOCK_NAME UNIQUE (STOCK_NAME)
);

CREATE TABLE STOCK_DETAIL (
	STOCK_ID	NUMBER			NOT NULL,
	COMP_NAME	VARCHAR(100)	NOT NULL,
	COMP_DESC	VARCHAR(255)	NOT NULL,
	REMARK		VARCHAR(225)	NOT NULL,
	LISTED_DATE	DATE			NOT NULL,
	CONSTRAINT FK_STOCK_ID FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID)
);

CREATE SEQUENCE STOCK_SEQ
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

-- no neeed to commit since Oracle Database issues an implicit COMMIT before and after any data definition language (DDL) statement.
