CREATE TABLE STOCK (
	STOCK_ID	NUMBER		NOT NULL,
	STOCK_CODE	VARCHAR(10)	NOT	NULL,
	STOCK_NAME	VARCHAR(20)	NOT	NULL,
	CONSTRAINT PK_STOCK_ID	PRIMARY KEY (STOCK_ID),
	CONSTRAINT STOCK_CODE UNIQUE (STOCK_CODE),
	CONSTRAINT STOCK_NAME UNIQUE (STOCK_NAME)
);

CREATE TABLE STOCK_DAILY_RECORD (
	RECORD_ID	NUMBER		NOT NULL,
	PRICE_OPEN	FLOAT		NULL,
	PRICE_CLOSE	FLOAT		NULL,
	PRICE_CHANGE	FLOAT	NULL,
	VOLUME		NUMBER		NULL,
	STOCK_DATE		DATE		NOT NULL,
	STOCK_ID	NUMBER		NOT NULL,
	CONSTRAINT PK_RECORD_ID	PRIMARY KEY (RECORD_ID),
	CONSTRAINT UK_STOCK_DATE UNIQUE (STOCK_DATE),
	CONSTRAINT FK_STOCK_ID FOREIGN KEY (STOCK_ID) REFERENCES STOCK(STOCK_ID) ON DELETE CASCADE
);

CREATE SEQUENCE STOCK_SEQ
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1
	CACHE 20;

CREATE SEQUENCE STOCK_DAILY_RECORD_SEQ
	MINVALUE 1
	START WITH 1
	INCREMENT BY 1
	CACHE 20;
	
-- no neeed to commit since Oracle Database issues an implicit COMMIT before and after any data definition language (DDL) statement.
